dev-rjw/geul-kkae-bi

- package.json
- pnpm-lock.yaml
- src/app/(find)/_components/ChangePasswordForm.tsx
- src/app/(find)/_components/FindPasswordForm.tsx
- src/app/(sign)/_components/SigninForm.tsx
- src/app/(sign)/_components/SignupForm.tsx
- src/schemas/commonSchema.ts
- src/schemas/signSchema.ts
- src/util/auth/client-action.ts
- src/util/user/client-action.ts
1. update:[signup] 비밀번호 변경 페이지 작업완료
2. update:[signup] 닉네임 중복체크 작업완료
3. update:[signin] 아이디 기억하기 작업완료
> 비밀번호 변경, 닉네임 중복체크, 아이디 기억하기

- .eslintrc.json
- src/app/games/rank/page.tsx
- src/app/layout.tsx
- src/app/page.tsx
> fix: vercel 오류 수정

- src/app/page.tsx
> fix : vercel 오류 수정

- src/app/(find)/_components/ChangePasswordForm.tsx
- src/app/(sign)/_components/EmailInput.tsx
- src/app/(sign)/_components/KakaoSignButtton.tsx
- src/app/(sign)/_components/SigninForm.tsx
- src/app/(sign)/_components/SignupForm.tsx
- src/app/auth/callback/route.ts
- src/components/HeaderInfoChange.tsx
- src/components/PasswordInput.tsx
- src/util/auth/client-action.ts
- src/util/user/server-action.ts
1. update:[signin] 소셜 회원에게 랜덤한 닉네임 부여하기
2. fix:[signup, signin] alert들 sweetalert2로 변경
> 소셜 회원 랜덤한 닉네임,  sweetalert2로 변경

- src/app/(sign)/_components/SignupForm.tsx
- src/app/auth/callback/route.ts
- src/util/user/server-action.ts
1. update:[signup] 회원가입시 기본 프로필이미지 넣기
> 기본 프로필 이미지 넣기

- src/app/games/(result)/_components/ResultSide.tsx
- src/app/games/speaking/_components/Question.tsx
> update:[speak] querystring 수정

- src/app/games/rank/page.tsx
> fix:[rank]chore

- src/app/games/rank/page.tsx
vercel 오류 나는부분 렌더링쪽에 쿼리 스트링 붙여서 해결하였습니다.
> fix:[rank]vercel오류 나는부분 찾아서 해결

- src/app/games/(result)/_components/ResultSide.tsx
- src/app/games/(result)/style.css
> update:[result] 결과 페이지 사이드 css 작업

- src/app/mypage/information/page.tsx
- src/app/mypage/page.tsx
> update:[mypage] 헤더 수정

- src/app/_components/MainRank.tsx
- src/app/mypage/_components/MypageMyRank.tsx
- src/app/mypage/_components/MypageMyScore.tsx
- src/utils/rank/client-action.ts
* fix: 마이페이지 새로고침 시 데이터 안나오는 현상 수정
* feat: week 계산 완료(고정된 값 제거) & 함수명 Top3로 수정
* fix: 지난주 순위, 내 랭킹 주차 일자 수정
> fix: 마이페이지 순위 데이터 및 주차 데이터 수정

- src/app/games/(result)/_components/GuestPage.tsx
- src/app/games/(result)/_components/ResultSide.tsx
- src/app/games/(result)/user/page.tsx
- src/app/games/(result)/utils/highlightScoreForMatchedGame.ts
- src/app/games/rank/page.tsx
- src/app/learning/page.tsx
- src/types/rank.ts
- src/types/result.ts
- src/utils/auth/server-action.ts
- src/utils/rank/server-action.ts
✅ 작업 사항
result와 rank 페이지 하기 사항 적용시켜 리팩토링 하였습니다.
확인 부탁드립니다. 
- 함수명 변경
- 주석 제거
- 데이터 페칭 로직 분리
- 타입명 수정
> refactor:[result,rank] 함수명 변경, 주석제거, 데이터 페칭 로직 분리, 타입명 수정

- src/app/learning/_components/WordCard.tsx
- src/app/learning/page.tsx
- src/types/learning.ts
✅ 변경사항
- 단어 카드 클릭시 해당 카드 디테일 정보 모달로 띄워주기 완료
- types 폴더안 learning.ts 파일생성 및  learning type 해당폴더로 이동 완료
상기내용 확인 바랍니다.
> feat:카드 클릭 시 해당 카드 디테일정보 모달로 띄워주기 완료 add: types 폴더 안 learning.ts 파일생성 

- src/app/(sign)/signin/page.tsx
- src/app/games/(result)/_components/Guest.tsx
- src/app/games/(result)/_components/ResultCard.tsx
- src/app/games/(result)/_components/ResultSide.tsx
- src/app/games/(result)/user/page.tsx
- src/app/globals.css
- src/app/share/url/page.tsx
- src/components/Header.tsx
> style: 공유페이지 기능, 반응형 작업 완료

- public/icon_speak_check.svg
- public/icon_speak_check_disable.svg
- public/icon_speak_wrong_btn.svg
- public/icon_speak_wrong_btn_disable.svg
- src/app/games/speaking/_components/Question.tsx
- src/app/games/wronganswer/_components/Pagination.tsx
- src/app/games/wronganswer/_components/SpeakAnswer.tsx
- src/app/games/wronganswer/style.css
- src/mutations/speek-mutation.ts
✅ 작업 사항
오답 페이지 css 수정
📸 스크린샷
- ![image](https://github.com/user-attachments/assets/6c13675f-4f3a-4606-a232-7e6423201593)
> style: 오답 페이지 css 수정

- src/app/games/wronganswer/_components/SpeakAnswer.tsx
- src/app/games/wronganswer/page.tsx
✅ 작업 사항
- 오답 페이지 모바일 css 작업
📸 스크린샷
> style: 오답 페이지 css 모바일 작업

- src/app/_components/MainCarousel.tsx
- src/components/Header.tsx
1. fix: 모바일, 비회원일때 공유하기 닉네임 undefinded인 문제 수정
2. style: 메인 슬라이드 모서리 수정
> fix: 모바일, 비회원일때 공유하기 닉네임 undefinded인 문제 수정, style: 메인 슬라이드 모서리 수정

- src/app/games/(result)/_components/ModalChecking.tsx
- src/app/games/(result)/_components/ModalWriting.tsx
- src/app/games/wronganswer/_components/WritingAnswer.tsx
- src/app/games/wronganswer/page.tsx
- src/app/globals.css
✅ 작업 사항
- 오답 페이지 css 수정
- 오답 팝업 css 수정
> style: 오답 관련 수정사항 css 반영

- src/app/games/wronganswer/_components/SpeakAnswer.tsx
> fix: 오답 페이지 삭제 코드 수정

- src/app/games/rank/_components/RankingTable.tsx
- src/app/games/rank/page.tsx
1. style: 랭킹 닉네임부분 width값 수정
2. style: 랭킹 하단 padding수정
> style: 랭킹 닉네임, 하단 간격 스타일 수정
